UPDATE productos SET alegra_id = 45 WHERE nombre = 'desinstalacion sistema CCTV o camaras de seguridad';
UPDATE productos SET alegra_id = 53 WHERE nombre = 'ABRAZADERA METAL DOBLE ALA 1/2';
UPDATE productos SET alegra_id = 46 WHERE nombre = 'alarma gsm, wifi inalambrica 99 zonas';
UPDATE productos SET alegra_id = 67 WHERE nombre = 'ANKOFEN';
UPDATE productos SET alegra_id = 63 WHERE nombre = 'ANKOFEN POMADA';
UPDATE productos SET alegra_id = 40 WHERE nombre = 'barilla roscada 5/16';
UPDATE productos SET alegra_id = 41 WHERE nombre = 'broca 5/16 muro';
UPDATE productos SET alegra_id = 66 WHERE nombre = 'cable neopreno';
UPDATE productos SET alegra_id = 18 WHERE nombre = 'cable UTP cat6 exterior';
UPDATE productos SET alegra_id = 61 WHERE nombre = 'cableado estructurado';
UPDATE productos SET alegra_id = 42 WHERE nombre = 'caja 10 x 10';
UPDATE productos SET alegra_id = 51 WHERE nombre = 'CAJA DE EMPALME TERCOL';
UPDATE productos SET alegra_id = 29 WHERE nombre = 'CAMARA 4 EN 1 TIPO BALA METALICA FULLCOLOR';
UPDATE productos SET alegra_id = 30 WHERE nombre = 'CAMARA 4 EN 1 TIPO BALA SEMIMETALICA FULLCOLOR LED 40M MIC';
UPDATE productos SET alegra_id = 12 WHERE nombre = 'Camara dahua 1080 aleación anti vandálica';
UPDATE productos SET alegra_id = 11 WHERE nombre = 'Camara hd dahua 1080 plastico';
UPDATE productos SET alegra_id = 64 WHERE nombre = 'camara ip ptz K7NIPC 5 MP';
UPDATE productos SET alegra_id = 14 WHERE nombre = 'Canaleta 13x7 dexxon';
UPDATE productos SET alegra_id = 43 WHERE nombre = 'Canaleta de piso';
UPDATE productos SET alegra_id = 24 WHERE nombre = 'cargador lenovo 20v 1.7 amp';
UPDATE productos SET alegra_id = 52 WHERE nombre = 'CONECTOR EMT 3/4';
UPDATE productos SET alegra_id = 65 WHERE nombre = 'CONVERTIDOR DE MEDIOS FBOP';
UPDATE productos SET alegra_id = 3 WHERE nombre = 'CPE220 MAXESTREAM 2.4';
UPDATE productos SET alegra_id = 10 WHERE nombre = 'Disco 2 therabites';
UPDATE productos SET alegra_id = 8 WHERE nombre = 'Disco duro 1 thera bite WD PURPLE';
UPDATE productos SET alegra_id = 57 WHERE nombre = 'DISCO DURO SSD M2 KINSTON';
UPDATE productos SET alegra_id = 23 WHERE nombre = 'display 15.6 lenovo';
UPDATE productos SET alegra_id = 13 WHERE nombre = 'Dvr dahua wize sense 1080p';
UPDATE productos SET alegra_id = 19 WHERE nombre = 'DVR HIK-VISION 8 CH 1080P';
UPDATE productos SET alegra_id = 48 WHERE nombre = 'FACE PLATE 1 PUERTO';